//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz_maker_models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorRexs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRexs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("quiz_maker_models.ErrorRexs", typeof(ErrorRexs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សំណួរ៖ {0} មិនអាចមានចម្លើយត្រឹមត្រុវលើសពីមួយ.
        /// </summary>
        public static string _MsgCorrectAnswerCannotBeMoreThanOne {
            get {
                return ResourceManager.GetString("_MsgCorrectAnswerCannotBeMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} មាន​{1} រួចហើយ.
        /// </summary>
        public static string _MsgDuplicateObject_Coloumns {
            get {
                return ResourceManager.GetString("_MsgDuplicateObject_Coloumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ធ្លាប់ប្រើប្រាស់មិនអាចលុបបាន.
        /// </summary>
        public static string _MsgInusedData {
            get {
                return ResourceManager.GetString("_MsgInusedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សំណួរ៖ {0}​ /r/n ត្រូវការចម្លើយយ៉ាងតិចមួយ.
        /// </summary>
        public static string _MsgMultipleChoiceOrCheckBoxAnswerRequireAnswerSet {
            get {
                return ResourceManager.GetString("_MsgMultipleChoiceOrCheckBoxAnswerRequireAnswerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សំណួរ៖ {0} មិនមានបញ្ជាក់ចម្លើយត្រឹមត្រុវ.
        /// </summary>
        public static string _MsgNoCorrrectAnswerFound {
            get {
                return ResourceManager.GetString("_MsgNoCorrrectAnswerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សំណួរ៖ {0} មិនមានបញ្ជាក់ពីពិន្ទុ.
        /// </summary>
        public static string _MsgScoreNotProvided {
            get {
                return ResourceManager.GetString("_MsgScoreNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សំណួរ៖ {0} ចម្លើយត្រឹមត្រូវបូកចូលគ្នាលើស  ពិន្ទុសរុប.
        /// </summary>
        public static string _MsgScoreWeightExceedMaximum {
            get {
                return ResourceManager.GetString("_MsgScoreWeightExceedMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សំណួរ៖ {0} ចម្លើយត្រឹមត្រុវបូកចូលគ្នាមិនគ្រប់  នៃពិន្ទុសរុប.
        /// </summary>
        public static string _MsgScoreWeightNotEnough {
            get {
                return ResourceManager.GetString("_MsgScoreWeightNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} មិនអាចទទេរបាន!.
        /// </summary>
        public static string _MsgValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("_MsgValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មិនអាចលុប Super User បានទេ!.
        /// </summary>
        public static string CannotRemoveSuperUser {
            get {
                return ResourceManager.GetString("CannotRemoveSuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មិនអាចស្វែងរកលំហាត់.
        /// </summary>
        public static string MsgCannotFindQuiz {
            get {
                return ResourceManager.GetString("MsgCannotFindQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to មិនអាចស្វែងរក​លំហាត់ លេខកូដ {0}.
        /// </summary>
        public static string MsgCannotFindQuizWithCode_ {
            get {
                return ResourceManager.GetString("MsgCannotFindQuizWithCode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizeToken និង RefreshToken មិនត្រឹមត្រូវ.
        /// </summary>
        public static string MsgInvalidAuthorizeTokenAndRefreshToken {
            get {
                return ResourceManager.GetString("MsgInvalidAuthorizeTokenAndRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken មិនត្រឹមត្រូវ.
        /// </summary>
        public static string MsgInvalidRefreshToken {
            get {
                return ResourceManager.GetString("MsgInvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizeToken មិនត្រឹមត្រូវ.
        /// </summary>
        public static string MsgInvalidToken {
            get {
                return ResourceManager.GetString("MsgInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះចូលប្រើប្រាស់ ឫលេខសម្ងាត់មិនត្រឹមត្រូវ!.
        /// </summary>
        public static string MsgInvalidUsernameOrPassoword {
            get {
                return ResourceManager.GetString("MsgInvalidUsernameOrPassoword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token មិនបានប្រើប្រាស់ជាមួយ អ្នកប្រើប្រាស់ណាមួយទេ.
        /// </summary>
        public static string MsgTokenNotAssignToAnyUser {
            get {
                return ResourceManager.GetString("MsgTokenNotAssignToAnyUser", resourceCulture);
            }
        }
    }
}
